### GET '/'
GET http://localhost:7777

### Register a new user -- POST /auth/register
POST http://localhost:7777/auth/register
Content-Type: application/json

{
  "username": "chris",
  "password": "mypass"
}

### Login a new user -- POST /auth/login
POST http://localhost:7777/auth/login
Content-Type: application/json

{
  "username": "chris",
  "password": "mypass"
}

### Fetch all todos -- GET /todos (protected)
GET http://localhost:7777/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY1NDIxNjE0LCJleHAiOjE3NjU1MDgwMTR9.o5_glrZmoPT040hTxks0e9xO0huWls36p71QLNVfc6A


### Creates a new todo -- POST /todos (protected)
POST http://localhost:7777/todos
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY1NDIxNjE0LCJleHAiOjE3NjU1MDgwMTR9.o5_glrZmoPT040hTxks0e9xO0huWls36p71QLNVfc6A

{
  "task": "Finish coding these projects"
}

### Update a todo -- PUT /todos/:id (protected)
PUT http://localhost:7777/todos/2?page=4 
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY1NDIxNjE0LCJleHAiOjE3NjU1MDgwMTR9.o5_glrZmoPT040hTxks0e9xO0huWls36p71QLNVfc6A

{
  "completed": 1
}

### Delete a todo -- DELETE /todos/:id (protected)
DELETE http://localhost:7777/todos/2 
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY1NDIxNjE0LCJleHAiOjE3NjU1MDgwMTR9.o5_glrZmoPT040hTxks0e9xO0huWls36p71QLNVfc6A